import { Id } from '../_generated/dataModel';

/**
 * Query Pipeline Type Definitions
 *
 * Type contracts for the RAG query pipeline that converts natural language
 * compliance questions into cited regulatory answers.
 */

/**
 * Input to the query pipeline.
 */
export interface QueryRequest {
  /** Natural language compliance question */
  question: string;
  /** Optional address for jurisdiction resolution (e.g., "1234 Main St, Houston, TX 77002") */
  address?: string;
  /** Optional conversation ID for context */
  conversationId?: Id<'conversations'>;
}

/**
 * Result of geocoding an address to jurisdictions.
 * Used to filter Pinecone queries by applicable regulatory bodies.
 */
export interface JurisdictionResult {
  /** Array of jurisdiction identifiers for filtering (e.g., ["US", "TX", "TX-48201", "TX-houston"]) */
  jurisdictions: string[];
  /** State code if resolved (e.g., "TX") */
  state?: string;
  /** County information if resolved */
  county?: {
    name: string;
    fips: string;
  };
  /** City name if resolved (e.g., "Houston") */
  city?: string;
  /** Raw Geocodio API response for debugging */
  raw: object;
}

/**
 * A chunk retrieved from Pinecone with metadata.
 * Represents a single regulatory text segment relevant to the query.
 */
export interface RetrievedChunk {
  /** Pinecone vector ID */
  id: string;
  /** Similarity score (0-1, higher is more similar) */
  score: number;
  /** Full text content of the chunk */
  text: string;
  /** Bluebook citation (e.g., "21 CFR 117.5") */
  citation: string;
  /** Jurisdiction identifier (e.g., "US", "TX-48201") */
  jurisdiction: string;
  /** Source type for regulatory hierarchy */
  sourceType: 'federal' | 'state' | 'county' | 'municipal';
  /** Section title or heading */
  title?: string;
  /** Regulatory category (e.g., "food-safety", "building-codes") */
  category?: string;
  /** Link to official source if available */
  url?: string;
}

/**
 * A citation reference in the generated answer.
 * Citations are numbered sequentially [1], [2], [3]...
 */
export interface Citation {
  /** Citation number (1-based for display as [1], [2], etc.) */
  id: number;
  /** Bluebook citation string */
  citation: string;
  /** Quoted text from source */
  text: string;
  /** Link to official source if available */
  url?: string;
  /** Jurisdiction identifier */
  jurisdiction: string;
  /** Source type for regulatory hierarchy */
  sourceType: 'federal' | 'state' | 'county' | 'municipal';
}

/**
 * A required permit or license identified in the answer.
 */
export interface Permit {
  /** Permit or license name (e.g., "Food Establishment Permit") */
  name: string;
  /** Government agency that issues the permit */
  issuingAgency: string;
  /** Jurisdiction identifier */
  jurisdiction: string;
  /** Link to application or information page if available */
  url?: string;
  /** Regulatory citation that requires this permit */
  citation: string;
}

/**
 * Confidence assessment for the generated answer.
 * Based on retrieval metrics, not LLM self-assessment.
 */
export interface ConfidenceScore {
  /** Human-readable confidence level */
  level: 'High' | 'Medium' | 'Low';
  /** Numeric confidence score (0-1) */
  score: number;
  /** Explanation of the confidence level */
  reason: string;
  /** Underlying metrics used to calculate confidence */
  metrics: {
    /** Average similarity score of retrieved chunks */
    avgSimilarity: number;
    /** Ratio of target jurisdictions represented in results */
    jurisdictionCoverage: number;
    /** Ratio of chunks with valid citations */
    citationCoverage: number;
  };
}

/**
 * Answer section for a specific jurisdiction level.
 * Separates federal, state, county, and municipal requirements.
 */
export interface JurisdictionSection {
  /** Jurisdiction level */
  level: 'federal' | 'state' | 'county' | 'municipal';
  /** Human-readable jurisdiction name (e.g., "Texas", "Harris County", "Houston") */
  jurisdictionName: string;
  /** Markdown-formatted answer content for this jurisdiction */
  content: string;
  /** Citations referenced in this section */
  citations: Citation[];
  /** Permits identified in this section */
  permits: Permit[];
}

/**
 * Structured answer generated by Claude.
 * Organizes regulations by jurisdiction hierarchy.
 */
export interface GeneratedAnswer {
  /** Brief summary of the answer (1-2 sentences) */
  summary: string;
  /** Jurisdiction-specific sections */
  sections: JurisdictionSection[];
  /** Consolidated list of all required permits */
  permits: Permit[];
  /** All citations used in the answer */
  citations: Citation[];
  /** Confidence assessment */
  confidence: ConfidenceScore;
}

/**
 * Complete output from the query pipeline.
 * Includes the question, jurisdictions, generated answer, and processing metadata.
 */
export interface QueryResult {
  /** Convex message ID if saved to database */
  queryId?: Id<'messages'>;
  /** Original user question */
  question: string;
  /** User-provided address if any */
  address?: string;
  /** Resolved jurisdictions for the query */
  jurisdictions: string[];
  /** Generated answer with citations and permits */
  answer: GeneratedAnswer;
  /** Retrieved chunks used to generate the answer */
  retrievedChunks: RetrievedChunk[];
  /** Pipeline execution time in milliseconds */
  processingTimeMs: number;
}
